#!/bin/bash
cd bin
#java Compiler.BPLScanner ../testFiles/example1.txt
#java Compiler.BPLParser ../testFiles/write5.bpl
#java Compiler.BPLTypeChecker ../testFiles/hiBob.bpl
java Compiler.BPLCodeGenerator ../testFiles/write5.bpl